const cartTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE'
}

export default cartTypes