const productTypes = {
    ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
    FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
    SET_PRODUCTS: 'SET_PRODUCTS',
    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
    SET_AVAILABLE_INGREDIENTS: 'SET_AVAILABLE_INGREDIENTS'
}

export default productTypes